export { default as DiscordSVG } from './discord';
export { default as GithubSVG } from './github';
export { default as InterestProtocolSVG } from './interest-protocol';
export { default as LogoSVG } from './logo';
export { default as LogoutSVG } from './logout';
export { default as TelegramSVG } from './telegram';
export { default as UserSVG } from './user';
export { default as WalletSVG } from './wallet';
export { default as XSVG } from './x';
